### ISSUE TITLE
Twine 2 support

### ISSUE THREAD

**Issue by chromebookbob** [daterre/UnityTwine#3]
The docs say this supports twine 2 but I'm struggling to get it to work. The plugin does not recognise links between pages, I think it is because the .twee format syntax is different for 2.0 than 1.4.

**Comment by daterre** [comment]
Unfortunately the docs fail to mention that only the popular SugarCane/SugarCube story format syntax is supported, not Harlowe (the new default in Twine 2). I really need to update the docs.
