### ISSUE TITLE
KeyNotFoundException on new scene

### ISSUE THREAD

**Issue by jamesShasha** [daterre/UnityTwine#7]
I'm trying to make a story that persists between scenes, so i can use different scenes for different sets / locations, but still have one .twee story overarching.

when i load a new scene, even if the story gameObject & my twine player are set to "dont destroy on load", i can't advance the story and my twine player is empty.

when i call Advance() i get a keynotfoundexception, even if i call Reset() just before.

any idea how to use a story over multiple scenes?

**Comment by daterre** [comment]
Could you please paste the entire error message from the console? Maybe you're doing it in a way I didn't anticipate.

In theory, this should work - as long as the script in which this hook is present is marked as DontDestoryOnLoad (othwerise it'll be destroyed when LoadLevelAsync completes and Resume will never be hit).

```
void SomePassage_Enter()
{
	story.Pause();
	yield return Application.LoadLevelAsync("anotherScene");
	story.Resume();
}
```

In my game I use a dedicated "Game" scene that includes a single object with the story + the following script. Its job is to switch scenes whenever a passage is entered with the tag `scene:anotherScene`. It also includes a DebugStart method that allows a specific scene to load this script in case it is started in the editor (very useful while developing). Hope it helps.

```
using UnityEngine;
using UnityTwine;
using System.Collections;

public class Game : MonoBehaviour {

	public string LoadedScene { get; private set; }
	public chapter1_simpler Story { get; private set; }
	
	public static Game Current { get; private set; }
	public static bool IsDebugStarting { get; private set; }

	void Awake()
	{
		GameObject.DontDestroyOnLoad(this.gameObject);
		Game.Current = this;
		LoadedScene = Application.loadedLevelName;

		Story = this.GetComponent<chapter1_simpler>();
		Story.OnOutput += Story_OnOutput;
	}

	void OnDestroy()
	{
		Story.OnOutput -= Story_OnOutput;
	}

	void Start()
	{
		if (!IsDebugStarting)
			Story.Begin();
	}

	public static AsyncOperation DebugStart()
	{
		IsDebugStarting = true;
		return Application.LoadLevelAdditiveAsync("0.game");
	}

	private void Story_OnOutput(TwineOutput output)
	{
		const string SCENE ="scene:";

		if (!(output is TwinePassage))
			return;

		var passage = (TwinePassage)output;
		for (int i = 0; i < passage.Tags.Length; i++)
		{
			string tag = passage.Tags[i];
			if (tag.StartsWith(SCENE))
			{
				string scene = tag.Substring(SCENE.Length);
				if (this.LoadedScene != scene)
					StartCoroutine(LoadScene(scene));
				break;
			}
		}
	}

	IEnumerator LoadScene(string name)
	{
		this.Story.Pause();
		GameObject.DontDestroyOnLoad(this.gameObject);
		yield return Application.LoadLevelAsync(name);
		LoadedScene = name;
		IsDebugStarting = false;
		this.Story.Resume();
	}
}
```

**Comment by jamesShasha** [comment]
it worked! thanks!

I rewrote my scene manager to work more like yours. I was using Application.LoadLevel; changing to Application.LoadLevelAsync and waiting until the scene is loaded to resume the story seems to have fixed it. My text player was reading the passage and creating the text in the old scene, which was then unloaded.
